### ISSUE TITLE
local wardrobe

### ISSUE THREAD

**Issue by meandred** [KittenApps/WCE#10]
the local wardrobe +288 don't seem to work, if it does where am I to find what it affects?

**Comment by KittenApps** [comment]
What do you exactly mean with doesn't work?

Aren't the 288 additional slots not added to the wardrobe? If yes than that's likely a compatibility issue with another addon. Please try to disable other addons until it work and report the conflicting addon here.

Or aren't outfits on page 9+ saved locally and lost after a reload? Than this is likely IndexedDB permission related.
