### ISSUE TITLE
Non-player characters and `allowLayeringWhileBound`

### ISSUE THREAD

**Issue by bananarama92** [KittenApps/WCE#11]
Heya, the `allowLayeringWhileBound` setting currently allows layering on both the player and non-player character, bypassing both the players restraints but also any locks that may or may not be present on the target (which, if actually locked, might otherwise prohibit the player from modifying the item). Is this intended behavior? 

If not, I'd recommend refactoring `Layering.Init` hook a bit, re-expressing the `Readonly` override in terms of a `Character.IsPlayer()` check.

```diff
const ret = next(args);
// @ts-ignore
- Layering.Readonly = args[4] && !fbcSettings.allowLayeringWhileBound;
+ if (args[2].IsPlayer() && fbcSettings.allowLayeringWhileBound) {
+     Layering.Readonly = false;
+ }
```

**Comment by KittenApps** [comment]
Yea ... that's planned. R105 isn't live yet anyway and that currently is just a quick test, because I had to fix nested function support in WCE first.
