### ISSUE TITLE
Anti Garble affecting people sans consent.

### ISSUE THREAD

**Issue by RosalynRussell** [KittenApps/WCE#14]
As per Ben on the Bondage Projects Discord, #rules-mods, "Do not code anything that can impact other players without their consent."

The Anti Garble feature is sending anti-garble to all players, even those with no mods at all. I do not want anti-garble, this is affecting me without my consent, and no way to disable it (and it should be opt-in, not out.).

**Comment by KittenApps** [comment]
On the sender side WCE gives you full control on how your messages are ungarbled and send to the chat, not violating any consent.

The recipient side is handled purely by BC (as you can see, that ungarbled messages will be show also to users who don't have WCE active and can also come from players using the role play difficulty ungarble restriction setting from BC).

If you want a feature to hide these original messages in chat, you have to raise an issue with BC devs and not here at WCE.

relevant code: https://gitgud.io/BondageProjects/Bondage-College/-/blob/389e6a7822bde92cd10db1e21748159759ccc6d0/BondageClub/Screens/Online/ChatRoom/ChatRoom.js#L4101-4103

**Comment by RosalynRussell** [comment]
Pre the BC garble changes I ran NO anti-garble (incoming) and ran a anti-anti-garble (outgoing) so people could not anti-garble me (without my consent). Now I am forced by WCE into the first option, without my consent. I did not consent to see ungarbled (non-ooc of course) messages. I will be taking this to the BC devs as you suggest.

**Comment by KittenApps** [comment]
Please read my answer. The ungarbling is done by BC and not by WCE.
This is only a cosmetic feature on your side of the BC client, which should be suggested as a feature request to BC.

Claiming that you not wanting to respect the free choice of other players (how they want their messages to be displayed) as violating your consent is something I'd also consider as trolling.

This issue tracker is for reporting bugs in WCE only, so please refrain from doing such claims here.
