### ISSUE TITLE
Closing the BP.io settings section doesn't remove the socket input field

### ISSUE THREAD

**Issue by zorgjbe** [KittenApps/WCE#18]
<img width="400" alt="Capture d’écran 2024-06-18 à 14 41 07" src="https://github.com/KittenApps/WCE/assets/90790349/ddac6bce-8d67-420e-af4a-de83c151f7dd">

**Comment by KittenApps** [comment]
it does for me, so that's like a incompatibility with another addon, could you try to find out which one by testing it with different sets of addons enabled?

**Comment by KittenApps** [comment]
oh it's when you exit with the esc key instead of clicking the exit button

**Comment by zorgjbe** [comment]
You're welcome~ And yeah, I just caught it by mistake, opening the screen since I had double logs from EBCH and was like "huh, why does it do that"

**Comment by zorgjbe** [comment]
Also, thank you for picking FBC back up. I don't think we've met on Discord, but 👍.

**Comment by KittenApps** [comment]
You're welcome.

Could you maybe look into https://gitlab.com/Sidiousious/bc-addon-loader/-/merge_requests/14 too. The extra bandwidth, which the unnecessary cache busting causes, is the only thing which stops me from recommending FUSAM as a installation method.
