### ISSUE TITLE
Chat input displacement

### ISSUE THREAD

**Issue by dDeepLb** [KittenApps/WCE#2]
![image](https://github.com/KittenApps/WCE/assets/71733861/4c77dfc2-8ee8-4823-a6fe-7d8f60d6507c)

**Comment by KittenApps** [comment]
> *these instructions are for r104+ only, for a still with r103 compatible version use the [old loader](https://kittenapps.github.io/fbc-fork/fbc.loader.user.js)*

You're clearly not on a current r104 beta version.
