### ISSUE TITLE
BUG: opening wardrobe opens it with additional slots even if setting is disabled

### ISSUE THREAD

**Issue by dDeepLb** [KittenApps/WCE#21]

**Comment by KittenApps** [comment]
I'm unable to reproduce this. Your wardrobe should be shrinked to the correct size as a side effect of disabling the extended wardrobe option by calling `WardrobeFixLength`. 

This doesn't work when `Player.Wardrobe` is still undefined but currently I se no realistically scenario how someone could access WCE settings and disable it while it's still not defined.

Another possible reason could be an incompatibility with an other addon, modifying the wardrobe too.

I'll need a reliable reproduction of this issue to debug it.

**Comment by dDeepLb** [comment]
currently disabled any mods that I had. 
when entering game, `Player.Wardrobe` is already initialized with 96 elements.
from 0 to 23, it has some data, everything else is null.
enabling and disabling extended wardrobe fixes that until next login.

<details>

<summary>Debug report</summary>

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
Game Version: R105
WebGL Version: webgl2
WCE Version: 6.3
Loaded via FUSAM: No
WCE Enabled Settings: 
- alternateArousal: true
- privateWardrobe: true
- automateCacheClear: true
- instantMessenger: true
- ctrlEnterOoc: true
- whisperInput: true
- chatColors: true
- pastProfiles: true
- pendingMessages: true
- lockpick: true
- allowLayeringWhileBound: true
- hideHiddenItemsIcon: true
- relogin: true
- version: 63
- shareAddons: true
- numericArousalMeter: true
- richOnlineProfile: true
- uwall: true
- animationEngine: true
- expressions: true
- activityExpressions: true
- layeringHide: true
- copyColor: true
- confirmWardrobeSave: true
- manualCacheClear: true
- augmentChat: true
- whisperTargetFixes: true
- antiGarbleChatLevel: full
- antiGarbleChatStutter: preserve
- antiGarbleChatBabyTalk: preserve
- antiGarbleWhisperLevel: full
- antiGarbleWhisperStutter: preserve
- antiGarbleWhisperBabyTalk: preserve
- autoStruggle: true
- customContentDomainCheck: true
- toySyncAddress: ws://127.0.0.1:12345
SDK Mods: 
- FUSAM @ 1ce8ec69
- WCE @ 6.3
Incomplete Functions: automaticExpressions, forcedClubSlave, hookBCXAPI
Modified Functions (non-SDK): 
Skipped Functionality for Compatibility: 
- 
Log: [INFO] Checking function integrity with GameVersion, R105
[DEBUG] loading settings
[INFO] using online settings
[DEBUG] handling settings side effects
[DEBUG] alternateArousal, true
[DEBUG] stutters, false
[DEBUG] extendedWardrobe, false
[DEBUG] privateWardrobe, false
[DEBUG] automateCacheClear, true
[DEBUG] instantMessenger, true
[DEBUG] ctrlEnterOoc, true
[DEBUG] whisperInput, true
[DEBUG] chatColors, true
[DEBUG] friendPresenceNotifications, false
[DEBUG] friendOfflineNotifications, false
[DEBUG] pastProfiles, true
[DEBUG] showSentMessages, true
[DEBUG] lockpick, true
[DEBUG] allowLayeringWhileBound, true
[DEBUG] allowIMBypassBCX, false
[DEBUG] blindWithoutGlasses, false
[DEBUG] leashAlways, false
[DEBUG] hideHiddenItemsIcon, true
[DEBUG] itemAntiCheat, false
[DEBUG] antiCheatBlackList, false
[DEBUG] relogin, true
[DEBUG] ghostNewUsers, false
[DEBUG] confirmLeave, false
[DEBUG] discreetMode, false
[DEBUG] friendNotificationsInChat, false
[DEBUG] shareAddons, true
[DEBUG] numericArousalMeter, true
[DEBUG] richOnlineProfile, true
[DEBUG] uwall, true
[DEBUG] animationEngine, true
[DEBUG] expressions, true
[DEBUG] activityExpressions, true
[DEBUG] layeringHide, false
[DEBUG] copyColor, false
[DEBUG] localWardrobe, false
[DEBUG] confirmWardrobeSave, false
[DEBUG] manualCacheClear, true
[DEBUG] augmentChat, true
[DEBUG] whisperTargetFixes, true
[DEBUG] antiGarbleChatoptions, false
[DEBUG] antiGarble, false
[DEBUG] antiGarbleChatoptions, false
[DEBUG] antiGarbleChatLevel, full
[DEBUG] antiGarbleChatoptions, preserve
[DEBUG] antiGarbleChatBabyTalk, preserve
[DEBUG] antiGarbleWhisperLevel, full
[DEBUG] antiGarbleWhisperStutter, preserve
[DEBUG] antiGarbleWhisperBabyTalk, preserve
[DEBUG] autoStruggle, true
[DEBUG] antiDeaf, false
[DEBUG] toySync, false
[DEBUG] customContentDomainCheck, true
[DEBUG] buttplugDevices, 
[DEBUG] toySyncAddress, ws://127.0.0.1:12345
[DEBUG] preventLayeringByOthers, false
[DEBUG] saving settings
[DEBUG] saved settings, {"alternateArousal":true,"stutters":false,"extendedWardrobe":false,"privateWardrobe":false,"automateCacheClear":true,"instantMessenger":true,"ctrlEnterOoc":true,"whisperInput":true,"chatColors":true,"friendPresenceNotifications":false,"friendOfflineNotifications":false,"pastProfiles":true,"pendingMessages":true,"lockpick":true,"allowLayeringWhileBound":true,"allowIMBypassBCX":false,"blindWithoutGlasses":false,"leashAlways":false,"hideHiddenItemsIcon":true,"itemAntiCheat":false,"antiCheatBlackList":false,"relogin":true,"ghostNewUsers":false,"confirmLeave":false,"discreetMode":false,"version":63,"friendNotificationsInChat":false,"shareAddons":true,"numericArousalMeter":true,"richOnlineProfile":true,"uwall":true,"animationEngine":true,"expressions":true,"activityExpressions":true,"layeringHide":false,"copyColor":false,"localWardrobe":false,"confirmWardrobeSave":false,"manualCacheClear":true,"augmentChat":true,"whisperTargetFixes":true,"antiGarble":false,"antiGarbleChatOptions":false,"antiGarbleChatLevel":"full","antiGarbleChatStutter":"preserve","antiGarbleChatBabyTalk":"preserve","antiGarbleWhisperLevel":"full","antiGarbleWhisperStutter":"preserve","antiGarbleWhisperBabyTalk":"preserve","autoStruggle":true,"antiDeaf":false,"toySync":false,"customContentDomainCheck":true,"buttplugDevices":"","toySyncAddress":"ws://127.0.0.1:12345","preventLayeringByOthers":false}
[DEBUG] {"alternateArousal":true,"stutters":false,"extendedWardrobe":false,"privateWardrobe":false,"automateCacheClear":true,"instantMessenger":true,"ctrlEnterOoc":true,"whisperInput":true,"chatColors":true,"friendPresenceNotifications":false,"friendOfflineNotifications":false,"pastProfiles":true,"pendingMessages":true,"lockpick":true,"allowLayeringWhileBound":true,"allowIMBypassBCX":false,"blindWithoutGlasses":false,"leashAlways":false,"hideHiddenItemsIcon":true,"itemAntiCheat":false,"antiCheatBlackList":false,"relogin":true,"ghostNewUsers":false,"confirmLeave":false,"discreetMode":false,"version":63,"friendNotificationsInChat":false,"shareAddons":true,"numericArousalMeter":true,"richOnlineProfile":true,"uwall":true,"animationEngine":true,"expressions":true,"activityExpressions":true,"layeringHide":false,"copyColor":false,"localWardrobe":false,"confirmWardrobeSave":false,"manualCacheClear":true,"augmentChat":true,"whisperTargetFixes":true,"antiGarble":false,"antiGarbleChatOptions":false,"antiGarbleChatLevel":"full","antiGarbleChatStutter":"preserve","antiGarbleChatBabyTalk":"preserve","antiGarbleWhisperLevel":"full","antiGarbleWhisperStutter":"preserve","antiGarbleWhisperBabyTalk":"preserve","autoStruggle":true,"antiDeaf":false,"toySync":false,"customContentDomainCheck":true,"buttplugDevices":"","toySyncAddress":"ws://127.0.0.1:12345","preventLayeringByOthers":false}
[DEBUG] initializing
[DEBUG] hooking struggle for lockpick cheat draw, {"Strength":{"DisablingCraftedProperty":"Strong"},"Flexibility":{"DisablingCraftedProperty":"Flexible"},"Dexterity":{"DisablingCraftedProperty":"Nimble"},"Loosen":{"DisablingCraftedProperty":"Nimble"},"LockPick":{}}
[DEBUG] registering additional commands
[DEBUG] layeringHide, true
[DEBUG] copyColor, true
[DEBUG] confirmWardrobeSave, true
[DEBUG] privateWardrobe, true
[DEBUG] currentSetting, customContentDomainCheck
[DEBUG] saving settings
[DEBUG] saved settings, {"alternateArousal":true,"stutters":false,"extendedWardrobe":false,"privateWardrobe":true,"automateCacheClear":true,"instantMessenger":true,"ctrlEnterOoc":true,"whisperInput":true,"chatColors":true,"friendPresenceNotifications":false,"friendOfflineNotifications":false,"pastProfiles":true,"pendingMessages":true,"lockpick":true,"allowLayeringWhileBound":true,"allowIMBypassBCX":false,"blindWithoutGlasses":false,"leashAlways":false,"hideHiddenItemsIcon":true,"itemAntiCheat":false,"antiCheatBlackList":false,"relogin":true,"ghostNewUsers":false,"confirmLeave":false,"discreetMode":false,"version":63,"friendNotificationsInChat":false,"shareAddons":true,"numericArousalMeter":true,"richOnlineProfile":true,"uwall":true,"animationEngine":true,"expressions":true,"activityExpressions":true,"layeringHide":true,"copyColor":true,"localWardrobe":false,"confirmWardrobeSave":true,"manualCacheClear":true,"augmentChat":true,"whisperTargetFixes":true,"antiGarble":false,"antiGarbleChatOptions":false,"antiGarbleChatLevel":"full","antiGarbleChatStutter":"preserve","antiGarbleChatBabyTalk":"preserve","antiGarbleWhisperLevel":"full","antiGarbleWhisperStutter":"preserve","antiGarbleWhisperBabyTalk":"preserve","autoStruggle":true,"antiDeaf":false,"toySync":false,"customContentDomainCheck":true,"buttplugDevices":"","toySyncAddress":"ws://127.0.0.1:12345","preventLayeringByOthers":false}

</details>

Also, report says that WCE wasn't loaded with FUSAM, but it was.

**Comment by KittenApps** [comment]
I hate how the FBC settings just calls all settings side effects during the initial load.

Thanks for your report.
