### ISSUE TITLE
Extended wardrobe fuckup

### ISSUE THREAD

**Issue by dDeepLb** [KittenApps/WCE#34]
Not sure when this did happen, but my friend got reset her WCE wardrobe, presumably after change to R107.
All additional slots were reset to state where outfits are just randomly generated.

**Comment by KittenApps** [comment]
Hmm ... extended wardrobe wasn't touched in 2 months, that must be something on BC side then?

https://github.com/KittenApps/WCE/commits/beta/src/functions/extendedWardrobe.ts

**Comment by dDeepLb** [comment]
![image](https://github.com/user-attachments/assets/c5c66477-e61f-41ef-951e-22f0392a4c82)

**Comment by KittenApps** [comment]
> `CharacterDecompressWardrobe` _is_ called on login though

That's not hooked.

Looking at the code, I currently see no way how that could have silently (without throwing an error) failed, esspecially since the same code worked fine for the last 2 months.
