### ISSUE TITLE
tab freezes in the background

### ISSUE THREAD

**Issue by codename-mute** [KittenApps/WCE#48]
```
xx:48:06.829 WCE 6.3.3: Clearing caches logger.ts:27:10
xx:48:06.829 WebGL: resetting canvas GLDraw.js:177:10
xx:48:06.970 WebGL: initialized as webgl2 GLDraw.js:78:10
xx:53:16.615 Script terminated by timeout at:
GLDrawRebuildCharacters@https://BC/R108/BondageClub/Scripts/GLDraw.js:193:18
GLDrawResetCanvas@https://BC/R108/BondageClub/Scripts/GLDraw.js:185:2
i@https://sidiousious.gitlab.io/bc-addon-loader/vendor/bcmodsdk.js:10:1214
l/r.router@https://sidiousious.gitlab.io/bc-addon-loader/vendor/bcmodsdk.js:10:2517
t@https://wce.netlify.app/wce.js:429:339
e@https://wce.netlify.app/wce.js:429:205
```

I've tried to analyse it on my end, but came back empty-handed. It's quite possible something is going wrong in the club functions, but this is the part of the code I never dived deep into before.

**Comment by KittenApps** [comment]
I've changed that the automatic cache clearing will one run when the window is in focus.
However I'd recommend disabling the `Clear Drawing Cache Hourly` option though and use the manual button if needed.

**Comment by codename-mute** [comment]
Yeah, I did disable the option. Maybe gonna check again after the change makes it to the next version of `WCE`.
