### ISSUE TITLE
Safe For Work Mode not Safe

### ISSUE THREAD

**Issue by dDeepLb** [KittenApps/WCE#58]
Only WCE. SFW Mode is enabled.
![image](https://github.com/user-attachments/assets/a20c42fc-58ea-4670-9a0c-4c1269e7faaa)

**Comment by dDeepLb** [comment]
also when you're disabling it, title and tab icon are not coming back.

**Comment by KittenApps** [comment]
I'd guess the asserts wer renamed and doesn't match the irgnored image source regex anymore:

```js
const ignoredImages = /(^Backgrounds\/(?!Sheet(White)?|grey|White\.|BrickWall\.)|\b(Kneel|Arousal|Activity|Asylum|Cage|Cell|ChangeLayersMouth|Diaper|Kidnap|Logo|Player|Remote|Restriction|SpitOutPacifier|Struggle|Therapy|Orgasm\d|Poses|HouseVincula|Seducer\w+)\b|^data:|^Assets\/(?!Female3DCG\/Emoticon\/(Afk|Sleep|Read|Gaming|Hearing|Thumbs(Up|Down))\/))/u;
```

Maybe we should consider just removing such barely used and mostly untrested functions.

**Comment by KittenApps** [comment]
So just to carify, previosuly the characters weren't drawn at all, right?

**Comment by dDeepLb** [comment]
yeah, that's correct
