### ISSUE TITLE
uwall whitelist option

### ISSUE THREAD

**Issue by Samael-dev** [KittenApps/WCE#6]
Little suggestion, think very helpfully because **uwall** is cool but **UltraBC** is helpful to be honest for special case and with trusted users want play together a whitelist member ID's can be great in my opinion like **LSGC** do on magics, breathplay or hypnosis.
The alternative maybe more easy fetch **BC** or **BCX** Owner and allow to bypass this.

![Capture_decran_2024-04-18_093924](https://github.com/KittenApps/WCE/assets/170186291/cb83378e-85d6-40ec-9e70-7133afccc1ce)

**Comment by KittenApps** [comment]
The online thing WCE does for uwall is to set `Player.OnlineSharedSettings.Uwall` to a boolean value.

https://github.com/KittenApps/WCE/blob/34d3b12c22bcee95811110f7945e550f5b0a8ec3/src/util/settings.js#L657-L667

This has to be implemented elsewhere.

**Comment by Samael-dev** [comment]
Have follow to **ULTRAbc** dev
https://github.com/KittenApps/WCE/issues/6#issue-2304101692
Thanks you!

**Comment by tetris245** [comment]
I've just released UBC 3.3 with this feature (named  Ulist):

* New commands:
  - mapz (target) to give coordinates in the map for specified target (yourself when not specified)
  - ulistadd (membernumber) to add a player to the list allowing to bypass Uwall
  - ulistremove (membernumber) to remove a player from the list allowing to bypass Uwall
  - ulistshow to display the list of players allowed to bypass Uwall
  - uset magictoys to enable/disable addition of vibes under locked chastity for trap mode in map rooms
* Added Ulist support to all commands (and wardrobe buttons) protected by Uwall
* Improved the traps in map rooms:
  - no removal of locked chastity items or locked toys in private zones
  - no addition of toys under locked chastity except if you have enabled the 'magictoys' mode
* Removed the self-whispering from the murmur command
* Updated the ustatus, xstatus bctw and xstatus thm commands

**Comment by KittenApps** [comment]
Okay, so the current plan is to add similar commands to WBC when Uwall is activated:

https://github.com/tetris245/ULTRAbc/commit/23505e5edb6d76252686da997fe2bc923499b42c
