### ISSUE TITLE
About Anti garble  Messages When turn it off and without an gag you speak always garble than

### ISSUE THREAD

**Issue by dragon011** [KittenApps/WCE#7]
![Bild_2024-05-19_013327505](https://github.com/KittenApps/WCE/assets/14083451/f6c06171-5642-45e0-94bf-cab082d613db)

By the way has not wear an gag and The Settings was Activate but off

And all normal messages make anti gable speak to anyways if you have activate it and no gag you speak always than with anti gable

**Comment by KittenApps** [comment]
Your garble level was `none`(always remove all garbled effects) and not `full` (do no ungarbling) as seen in the picture. And it correctly removed the stutter effect (cause the `preserve shutter` option in settings was likely also not checked).

Please read the documentation: https://github.com/KittenApps/WCE/wiki/Anti-Garble-system

**Comment by dragon011** [comment]
But shouldn't such a garble effect occur with none? If you have no gag in your mouth and you have the 2 garble options on, but they are set to none, so to speak?
